//! This module defines the procedural macro that generates typescript bindings for
//! Rust items.

// TODO see if https://github.com/tauri-apps/tauri-bindgen is better

use fd_lock::{RwLock, RwLockWriteGuard};
use proc_macro2::TokenStream;
use quote::ToTokens;
use std::fs::File;
use std::io::{Read, Seek, SeekFrom, Write};
use std::path::PathBuf;
use syn::Meta::NameValue;
use syn::{Attribute, ItemStruct, LitStr, PathArguments::AngleBracketed, Type, TypePath, parse};
use syn::{Fields, FieldsNamed, GenericArgument};

/// This is the header that will be written to the generated TypeScript declaration
/// file.
const TS_FILE_HEADER: &str = "/**
 * @file  index.d.ts
 * @brief This file contains the TypeScript bindings for Rust items used by the
 *        Torii application.
 * @note  This file is generated by torii-desktop-macro. Do not edit manually.
 */
";

/// A procedural macro that generates typescript bindings for the annotated Rust item.
///
/// This will generate a TypeScript declaration file (.d.ts) for the item, allowing it
/// to be used in TypeScript code.
///
/// # Example
///
/// ```
/// use std::collections::HashMap;
/// use torii_desktop_macro::ts_bind;
///
/// #[ts_bind()]
/// struct EmptyStruct {}
///
/// /// Complex fields
/// #[ts_bind()]
/// struct TestStruct {
///     field1: String,
///     field2: Option<i32>,
///     field3: Option<String>,
///     field4: Vec<f64>,
///     field5: HashMap<f64, String>,
///     /// Hashmap to optional booleans.
///     field6: HashMap<String, Option<bool>>,
///     field7: HashMap<String, Option<Vec<f64>>>,
///     /// Vector of vectors.
///     field8: Vec<Vec<Vec<f64>>>,
///     field9: Option<Vec<Option<Vec<Vec<f64>>>>>,
/// }
/// ```
pub(crate) fn bind_struct(mut strucc: ItemStruct) -> TokenStream {
    let directory = caller_bindings_directory();
    let build_hash = get_build_hash();

    let build_file_path = directory.join(".build-id");
    let mut build_lock = lock_file(build_file_path);
    let mut build_guard = build_lock.write().unwrap();
    let previous_build_hash = read_text_file(&mut build_guard).unwrap_or_default();

    let bindings_file_path = directory.join("index.d.ts");
    let mut bindings_lock = lock_file(bindings_file_path);
    let mut bindings_guard = bindings_lock.write().unwrap();

    // Cheeck if build hashes match, otherwise remove `index.d.ts` with stub and write
    // new build hash to `.build-id` file.
    if build_hash != previous_build_hash {
        overwrite(&mut build_guard, build_hash)
            .expect("Failed to overwrite build hash to .build-id file.");
        overwrite(&mut bindings_guard, TS_FILE_HEADER)
            .expect("Failed to overwrite index.d.ts file.");
    }

    // The code above ensures that some kind of "main" was triggered. We can now safely
    // append the **current** item [strucc] to the `index.d.ts` file.

    // Seek end of file to append and write a new line to separate the previous item
    // from the current one.
    bindings_guard
        .seek(SeekFrom::End(0))
        .expect("Failed to seek to end of index.d.ts file.");
    bindings_guard
        .write_all("\n".as_bytes())
        .expect("Failed to write documentation to index.d.ts file.");

    /// Retrieves the documentation comments as lines of text from the given attributes.
    fn get_documentation_lines(attrs: &Vec<Attribute>) -> Vec<String> {
        attrs
            .iter()
            .filter(|attr| attr.path().is_ident("doc"))
            .filter_map(|attr| match &attr.meta {
                NameValue(meta_name_value) => {
                    parse::<LitStr>(meta_name_value.value.to_token_stream().into())
                        .ok()
                        .map(|f| f.value())
                }
                _ => None,
            })
            .map(|line| line.trim().to_string())
            .collect::<Vec<_>>()
    }

    /// Retrieves the documentation comments as a single string of text from the given
    /// attributes. If there is no documentation, it will return `None`. If there is one
    /// line of documentation, it will be inlined.
    fn get_documentation(attrs: &Vec<Attribute>) -> Option<String> {
        let lines = get_documentation_lines(&attrs);
        match lines.len() {
            0 => None,
            1 => Some(format!("/** {} */\n", lines[0])),
            _ => Some(format!(
                "/**\n{}\n */\n",
                lines
                    .iter()
                    .map(|f| format!(" * {f}"))
                    .collect::<Vec<_>>()
                    .join("\n")
            )),
        }
    }

    let type_documentation = get_documentation(&strucc.attrs).unwrap_or("\n".to_string());
    bindings_guard
        .write_all(type_documentation.as_bytes())
        .expect("Failed to write documentation to index.d.ts file.");

    if strucc.fields.len() == 0 {
        bindings_guard
            .write_all(format!("export interface {} {{}}\n", strucc.ident.to_string()).as_bytes())
            .expect("Failed to write interface to index.d.ts file.");
    } else {
        bindings_guard
            .write_all(format!("export interface {} {{\n", strucc.ident.to_string()).as_bytes())
            .expect("Failed to write interface header to index.d.ts file.");
    }

    for (index, field) in strucc.fields.iter().enumerate() {
        let field_documentation = get_documentation(&field.attrs)
            .map(|docs| {
                docs.lines()
                    .map(|f| format!("\t{f}\n"))
                    .collect::<Vec<_>>()
                    .join("")
            })
            .unwrap_or("\n".to_string());

        if field_documentation.trim().is_empty() {
            /* do nothing */
        } else if index > 0 && !field_documentation.trim().is_empty() {
            bindings_guard
                .write_all("\n".as_bytes())
                .expect("Failed to write documentation to index.d.ts file.");
            bindings_guard
                .write_all(field_documentation.as_bytes())
                .expect("Failed to write documentation to index.d.ts file.");
        } else {
            bindings_guard
                .write_all(field_documentation.as_bytes())
                .expect("Failed to write documentation to index.d.ts file.");
        }

        let field_name = field.ident.as_ref().unwrap().to_string();
        let field_type = rs_type_to_ts(&field.ty);

        // if is_optional(&field.ty) {
        //     field_type = format!("{} | undefined", field_type);
        // }

        bindings_guard
            .write_all(format!("\t{}: {};\n", field_name, field_type).as_bytes())
            .expect("Failed to write documentation to index.d.ts file.");
    }

    if strucc.fields.len() > 0 {
        bindings_guard
            .write_all("}\n".as_bytes())
            .expect("Failed to write interface footer to index.d.ts file.");
    }

    // Remove all fields with the `#[ts_only]` attribute from the struct, so that they are
    // not included in the Rust code.
    let fields = strucc
        .fields
        .into_iter()
        .filter(|field| {
            !field
                .attrs
                .iter()
                .any(|attr| attr.path().is_ident("ts_only"))
        })
        .collect::<Vec<_>>();
    strucc.fields = Fields::Named(FieldsNamed {
        brace_token: syn::token::Brace::default(),
        named: fields.into_iter().collect(),
    });

    strucc.to_token_stream()
}

/// This function ensures that the directory exists and creates a `.gitignore` file to
/// ignore all files in it. The typescript bindings will be generated in the
/// `$WORKSPACE/typescript` directory.
///
/// ```txt
/// api/
/// ├── typescript/
/// |   ├── .gitignore
/// │   └── ...
/// ├── src/
/// │   └── ...
/// └── Cargo.toml
/// ```
fn caller_bindings_directory() -> PathBuf {
    let path = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("typescript");
    std::fs::create_dir_all(&path).expect("Failed to create typescript directory.");
    std::fs::write(&path.join(".gitignore"), ".build-id\n.gitignore")
        .expect("Failed to write .gitignore file.");
    path
}

/// Cross-thread singleton that returns a unique build hash for the current build.
///
/// This is used to ensure that the generated TypeScript bindings are unique for
/// each build and redrawn when the build changes. The build hash is of the format
/// `<process_id>-<timestamp>`, where `process_id` is the current process ID and
/// `timestamp` is the current timestamp in milliseconds.
fn get_build_hash() -> String {
    match std::env::var("YOOSO_BUILD_HASH") {
        Ok(hash) => hash,
        Err(_) => {
            let timestamp = format!("{}", chrono::Utc::now().timestamp_millis());
            let process_id = std::process::id();
            let hash = format!("{}-{}", process_id, timestamp);

            unsafe {
                std::env::set_var("YOOSO_BUILD_HASH", &hash);
            }

            hash
        }
    }
}

/// Open the file and create it if not exists. It will be locked in a cross-thread
/// lock to prevent side effects.
fn lock_file(path: PathBuf) -> RwLock<File> {
    let openapi_file = File::options()
        .read(true)
        .write(true)
        .create(true)
        .open(path)
        .expect("Failed to open openapi.json file.");

    RwLock::new(openapi_file)
}

/// Reads the contents of the file from the given lock guard and parses it as JSON. If the
/// file is empty or invalid JSON, it will return an error.
fn read_text_file(guard: &mut RwLockWriteGuard<File>) -> std::io::Result<String> {
    let mut content = String::new();
    guard.read_to_string(&mut content)?;
    Ok(content)
}

/// Reads the contents of the file from the given lock guard and parses it as JSON. If the
/// file is empty or invalid JSON, it will return an error.
fn overwrite<T: AsRef<str>>(guard: &mut RwLockWriteGuard<File>, content: T) -> std::io::Result<()> {
    guard.seek(SeekFrom::Start(0))?;
    guard.set_len(0)?;
    guard.write_all(content.as_ref().as_bytes())?;
    guard.flush()
}

/// Converts a Rust type to a TypeScript type. This is a simplified version and may not
/// cover all cases.
fn rs_type_to_ts(ty: &Type) -> String {
    match ty {
        Type::Path(TypePath { path, .. }) => {
            let last_segment = path
                .segments
                .last()
                .expect("Expected a type path to have at least one segment.");
            let arguments = &last_segment.arguments;
            let ident_str = last_segment.ident.to_string();

            match ident_str.as_str() {
                "Option" => {
                    let generics = match arguments {
                        AngleBracketed(angle_bracketed) => &angle_bracketed.args,
                        _ => return "any".to_string(),
                    };

                    if let Some(GenericArgument::Type(inner_ty)) = generics.first() {
                        return format!("({} | undefined)", rs_type_to_ts(inner_ty));
                    }

                    "any".to_string()
                }
                "bool" => "boolean".to_string(),
                "usize" | "isize" | "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64"
                | "f32" | "f64" => "number".to_string(),
                "String" | "str" | "PathBuf" => "string".to_string(),
                "Vec" => {
                    let generics = match arguments {
                        AngleBracketed(angle_bracketed) => &angle_bracketed.args,
                        _ => return "any[]".to_string(),
                    };

                    if let Some(GenericArgument::Type(inner_ty)) = generics.first() {
                        return format!("{}[]", rs_type_to_ts(inner_ty));
                    }

                    "any[]".to_string()
                }
                "HashMap" => {
                    let generics = match arguments {
                        AngleBracketed(angle_bracketed) => &angle_bracketed.args,
                        _ => return "{ [key: string]: any }".to_string(),
                    };

                    if let Some(GenericArgument::Type(key_ty)) = generics.first() {
                        if let Some(GenericArgument::Type(value_ty)) = generics.iter().nth(1) {
                            return format!(
                                "{{ [key: {}]: {} }}",
                                rs_type_to_ts(key_ty),
                                rs_type_to_ts(value_ty),
                            );
                        }
                    }

                    "{ [key: string | number]: any }".to_string()
                }
                _ => ident_str,
            }
        }
        _ => "any".to_string(),
    }
}
