<template>
    <div class="view-component-article-editor">
        <editor-content
            class="file-editor-md"
            @click="onEditorClick"
            :editor="editor"
        />
        <markdown-editor-autocomplete
            ref="autocompletePopup"
            :editor-view="editor.view"
            :suggestions="suggestions"
            @select="onSuggestionSelect"
        />
        <!-- <div v-else class="placeholder">
            <NIcon size="32">
                <TextOutline />
            </NIcon>
            Article
        </div> -->
    </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { Editor, EditorContent } from '@tiptap/vue-3';
import { Markdown } from '@tiptap/markdown';
import { TaskList, TaskItem } from '@tiptap/extension-list';
import { NIcon } from 'naive-ui';
import { CloseOutline, TextOutline } from '@vicons/ionicons5';
import { openUrl } from '@tauri-apps/plugin-opener';
import normalizeurl from 'normalizeurl';

// tiptap extensions
import StarterKit from '@tiptap/starter-kit';
import {
    AutocompleteExtension,
    type SuggestionItem,
} from './autocomplete-extension.ts';
import MarkdownEditorAutocomplete from './MarkdownEditorAutocomplete.vue';
import type { Record } from '../../types';
import { getRecordComponent, saveRecordComponent } from '@/services/recordsService.ts';

const props = defineProps<{
    record: Record;
    // placeholder: boolean;
    viewMode?: 'edit' | 'preview';
    autocompleteStart: () => Promise<void>;
    autocompleteSuggestion: (name: string) => Promise<SuggestionItem[]>;
}>();

const emit = defineEmits<{
    (e: 'open-file', record: Record): void;
    (e: 'update:wordCount', value: number): void;
}>();

const autocompletePopup = ref<InstanceType<
    typeof MarkdownEditorAutocomplete
> | null>(null);

const suggestions = ref<SuggestionItem[]>([]);
const viewMode = computed(() => props.viewMode || 'edit');

const ignoreFirstSave = ref(true);
const editor = new Editor({
    extensions: [
        Markdown,
        StarterKit,
        TaskList,
        TaskItem,
        AutocompleteExtension.configure({
            cache: async () => {
                return props.autocompleteStart();
            },
            suggest: async (name: string) => {
                return props.autocompleteSuggestion(name);
            },
            replace: (item) => ({
                type: 'text',
                marks: [
                    {
                        type: 'link',
                        attrs: {
                            href: `./${encodeURIComponent(item.value)}.md`,
                        },
                    },
                ],
                text: item.label,
            }),
            extractToken: (text) => {
                const match = text.match(/[a-zA-Z0-9_.]+$/);
                return match ? match[0] : null;
            },
            popup: autocompletePopup,
        }),
    ],
    content: '', // Initial content is empty; will be loaded in onMounted
    // content:
    //     '<h1>STOP!!!</h1><p>IF YOU SEE THIS DO NOT EDIT THIS FILE!!! AN ERROR OCCURED ' +
    //     'AND EDITING THIS FILE CAN CAUSE DATA LOSS!!! RELOAD THE APPLICATION!!!</p>',
    onUpdate: () => {
        saveFile();
        updateWordCount();
    },
});

watch(
    () => viewMode.value,
    (newMode) => {
        if (newMode === 'preview') {
            editor.setEditable(false);
        } else {
            editor.setEditable(true);
        }
    },
    { immediate: true }
);

/**
 * Handles click
 */
function onLinkClick(event: MouseEvent) {
    // if (!event.ctrlKey && !event.metaKey) return;

    const link = (event.target as HTMLElement).closest('a');
    if (!link) return;

    event.preventDefault();
    event.stopPropagation();

    const href = link.getAttribute('href');
    if (!href) return;
    const path = decodeURIComponent(href);

    // If href starts with "./", it's a path relative to the current file. We need
    // to resolve it to an absolute path.
    if (path.startsWith('./')) {
        const currentFilePath = props.record?.relative_path;
        if (!currentFilePath) return;

        const lastSlash = currentFilePath.lastIndexOf('/');
        const recordParent = lastSlash === -1 ? '.' : currentFilePath.substring(0, lastSlash);

        const newPath = normalizeurl(`${recordParent}/${path}`);

        console.log('[todo: open relative path]', recordParent, path, newPath);
        console.warn(`Relative hyperlink '${path}' is temporarily disabled due to client refactor.`);
        return;
    }

    // If href is a remote URL (starts with http:// or https://), open it in the default browser.
    if (path.startsWith('http://') || path.startsWith('https://')) {
        if (viewMode.value === 'preview') {
            openUrl(path);
        }
        return;
    }

    console.error(`Opening hyperlink '${path}' is not currently supported.`);

    // const fileName = decodeURIComponent(match[1]);
    // emit('open-file', fileName);
}

onMounted(async () => {
    // Load the file content when the component is mounted.
    await loadFile();
    autocompletePopup.value?.hide();

    // Start listening after mounted.
    editor.on('focus', () => {
        autocompletePopup.value?.show();
        autocompletePopup.value?.realign();
    });

    editor.on('selectionUpdate', () => {
        autocompletePopup.value?.realign();
    });

    const dom = editor.view.dom;
    dom.addEventListener('click', onLinkClick, { capture: true });
});

watch(
    () => props.record,
    async (record: any) => {
        if (!record) return;

        // Load the file content when a new file is selected
        let bytes = await getRecordComponent<Uint8Array>(props.record, 'article');
        let content = new TextDecoder().decode(bytes);

        ignoreFirstSave.value = true;
        editor.commands.setContent(content, { contentType: 'markdown' });
    }
);

async function loadFile() {
    let bytes = await getRecordComponent<Uint8Array>(props.record, 'article');
    let content = new TextDecoder().decode(bytes);

    ignoreFirstSave.value = true;
    editor.commands.setContent(content, { contentType: 'markdown' });
}

async function saveFile() {
    if (!props.record) return;
    if (ignoreFirstSave.value) {
        ignoreFirstSave.value = false;
        return;
    }

    // Get markdown content from the editor
    const content = editor.getMarkdown();
    // console.debug('save', content);

    // Save the file content whenever it changes
    await saveRecordComponent(props.record, 'article', content, 'text/markdown');
}

// Compute word count from the editor (e.g., on update)
function updateWordCount() {
    const text = editor?.getText() || '';
    const words = text.trim() ? text.trim().split(/\s+/).length : 0;
    emit('update:wordCount', words);
}

function onScrollProjectContent(event: Event) {
    autocompletePopup.value?.hide();
}

// Call command from autocomplete extension.
async function onSuggestionSelect(item: SuggestionItem) {
    editor.commands.autocomplete(item);
}

async function onEditorClick() {
    // Focus the editor when the user clicks on it
    editor.commands.focus();
}

onUnmounted(() => {
    const dom = editor.view.dom;
    dom.removeEventListener('click', onLinkClick, { capture: true });
    editor.destroy();
});

defineExpose({
    onScrollProjectContent,
});
</script>

<style lang="scss" scoped>
.view-component-article-editor {
    display: flex;
    flex-direction: column;
    width: 100%;
    height: 100%;

    // .placeholder {
    //     position: relative;
    //     display: flex;
    //     flex-direction: row;
    //     justify-content: center;
    //     align-items: end;
    //     gap: 8px;
    //     border: 2px dashed #ccc;
    //     border-radius: 8px;
    //     margin: 0 16px;
    //     padding: 16px;
    //     box-sizing: border-box;
    // }
}
</style>

<!-- Override TipTap Editor (Global Style) -->
<style lang="scss">
.file-editor-md {
    width: 100%;
    height: 100%;
    box-sizing: border-box;
    padding: 0 16px;
    cursor: text;

    .ProseMirror {
        outline: none;
    }

    p {
        padding: 0;
        margin: 0;
    }

    label,
    input[type='checkbox'] {
        display: inline;
    }

    li * {
        display: inline;
    }

    li[data-checked] {
        list-style-type: none;
    }
}
</style>
