<template>
    <div class="view-component-article-editor">
        <editor-content
            class="file-editor-md"
            @click="onEditorClick"
            :editor="editor"
        />
        <markdown-editor-autocomplete
            ref="autocompletePopup"
            :editor-view="editor.view"
            :suggestions="[{ label: 'Test' }]"
            @select="console.log('selected', $event)"
        />
    </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue';
import { invoke } from '@tauri-apps/api/core';
import { Editor, EditorContent } from '@tiptap/vue-3';
import { Markdown } from '@tiptap/markdown';
import { TaskList, TaskItem } from '@tiptap/extension-list';

// tiptap extensions
import StarterKit from '@tiptap/starter-kit';
import {
    AutocompleteExtension,
    type SuggestionItem,
} from './autocomplete-extension';
import MarkdownEditorAutocomplete from './MarkdownEditorAutocomplete.vue';

const props = defineProps<{
    directory: string | null;
    name: string | null;
    autocompleteSuggestion: (name: string) => Promise<SuggestionItem[]>;
}>();

const autocompletePopup = ref<InstanceType<
    typeof MarkdownEditorAutocomplete
> | null>(null);

const ignoreFirstSave = ref(true);
const editor = new Editor({
    extensions: [
        Markdown,
        StarterKit,
        TaskList,
        TaskItem,
        AutocompleteExtension.configure({
            suggest: async (name: string) => {
                const suggestions = await props.autocompleteSuggestion(name);
                return suggestions;
            },
            replace: (item) => ({
                type: 'text',
                marks: [
                    {
                        type: 'link',
                        attrs: {
                            href: `./${encodeURIComponent(item.label)}.md`,
                        },
                    },
                ],
                text: item.label,
            }),
            extractToken: (text) => {
                const match = text.match(/[a-zA-Z0-9_.]+$/);
                return match ? match[0] : null;
            },
        }),
    ],
    content: '', // Initial content is empty; will be loaded in onMounted
    // content:
    //     '<h1>STOP!!!</h1><p>IF YOU SEE THIS DO NOT EDIT THIS FILE!!! AN ERROR OCCURED ' +
    //     'AND EDITING THIS FILE CAN CAUSE DATA LOSS!!! RELOAD THE APPLICATION!!!</p>',
    onUpdate: saveFile,
});

editor.on('focus', () => {
    autocompletePopup.value?.show();
    autocompletePopup.value?.realign();
});

editor.on('selectionUpdate', () => {
    autocompletePopup.value?.realign();
});

onMounted(async () => {
    // Load the file content when the component is mounted.
    await loadFile();

    // Hide the autocomplete popup (load file triggers autocomplete show)
    autocompletePopup.value?.hide();
});

watch(
    () => props.name,
    async (name: string | null) => {
        if (!name) return;

        // Load the file content when a new file is selected
        let bytes = await invoke('get_record_component', {
            directory: props.directory,
            name,
            component: 'article',
        });
        let content = new TextDecoder().decode(bytes as Uint8Array);
        console.debug('load', content);

        ignoreFirstSave.value = true;
        editor.commands.setContent(content, { contentType: 'markdown' });
    }
);

async function loadFile() {
    let bytes = await invoke('get_record_component', {
        directory: props.directory,
        name: props.name,
        component: 'article',
    });
    console.log(bytes);
    let content = new TextDecoder().decode(bytes as Uint8Array);
    console.debug('load', content);

    ignoreFirstSave.value = true;
    editor.commands.setContent(content, { contentType: 'markdown' });
}

async function saveFile() {
    if (!props.directory) return;
    if (!props.name) return;
    if (ignoreFirstSave.value) {
        ignoreFirstSave.value = false;
        return;
    }

    // Get markdown content from the editor
    const content = editor.getMarkdown();
    console.debug('save', content);

    // Save the file content whenever it changes
    await invoke('save_record_component', {
        directory: props.directory,
        name: props.name,
        component: 'article',
        content,
    });
}

async function onEditorClick() {
    // Focus the editor when the user clicks on it
    editor.commands.focus();
}

onUnmounted(() => {
    editor.destroy();
});
</script>

<style lang="scss">
.view-component-article-editor {
    width: 100%;
    height: 100%;
}

.file-editor-md {
    width: 100%;
    height: 100%;
    box-sizing: border-box;
    padding: 16px;

    .ProseMirror {
        outline: none;
    }

    p {
        padding: 0;
        margin: 0;
    }

    label,
    input[type='checkbox'] {
        display: inline;
    }

    li * {
        display: inline;
    }

    li[data-checked] {
        list-style-type: none;
    }
}
</style>
