<template>
    <editor-content
        class="file-editor-md"
        @click="onEditorClick"
        :editor="editor"
    />
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue';
import { invoke } from '@tauri-apps/api/core';
import { Editor, EditorContent } from '@tiptap/vue-3';
import { Markdown } from '@tiptap/markdown';
import { TaskList, TaskItem } from '@tiptap/extension-list';
import StarterKit from '@tiptap/starter-kit';

const props = defineProps<{
    directory: string | null;
    name: string | null;
}>();

const ignoreFirstSave = ref(true);
const editor = new Editor({
    extensions: [Markdown, StarterKit, TaskList, TaskItem],
    content:
        '<h1>STOP!!!</h1><p>IF YOU SEE THIS DO NOT EDIT THIS FILE!!! AN ERROR OCCURED ' +
        'AND EDITING THIS FILE CAN CAUSE DATA LOSS!!! RELOAD THE APPLICATION!!!</p>',
    onUpdate: saveFile,
});

onMounted(loadFile);

watch(
    () => props.name,
    async (name: string | null) => {
        if (!name) return;

        // Load the file content when a new file is selected
        let content = await invoke<string>('get_record_component', {
            directory: props.directory,
            name,
            component: 'article',
        });
        console.debug('load', content);

        ignoreFirstSave.value = true;
        editor.commands.setContent(content, { contentType: 'markdown' });
    }
);

async function loadFile() {
    let content = await invoke<string>('get_record_component', {
        directory: props.directory,
        name: props.name,
        component: 'article',
    });
    console.debug('load', content);

    ignoreFirstSave.value = true;
    editor.commands.setContent(content, { contentType: 'markdown' });
}

async function saveFile() {
    if (!props.directory) return;
    if (!props.name) return;
    if (ignoreFirstSave.value) {
        ignoreFirstSave.value = false;
        return;
    }

    // Get markdown content from the editor
    const content = editor.getMarkdown();
    console.debug('save', content);

    // Save the file content whenever it changes
    await invoke('save_record_component', {
        directory: props.directory,
        name: props.name,
        component: 'article',
        content,
    });
}

async function onEditorClick() {
    // Focus the editor when the user clicks on it
    editor.commands.focus();
}

onUnmounted(() => {
    editor.destroy();
});
</script>

<style lang="scss">
.file-editor-md {
    width: 100%;
    height: 100%;
    box-sizing: border-box;
    padding: 16px;

    .ProseMirror {
        outline: none;
    }

    p {
        padding: 0;
        margin: 0;
    }

    label,
    input[type='checkbox'] {
        display: inline;
    }

    li * {
        display: inline;
    }

    li[data-checked] {
        list-style-type: none;
    }
}
</style>
