<template>
    <editor-content class="file-editor-md" :editor="editor" />
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue';
import { invoke } from '@tauri-apps/api/core';
import { Editor, EditorContent } from '@tiptap/vue-3';
import { Markdown } from '@tiptap/markdown';
import StarterKit from '@tiptap/starter-kit';

const props = defineProps<{
    file: string;
}>();

const ignoreFirstSave = ref(true);
const editor = new Editor({
    extensions: [Markdown, StarterKit],
    content:
        '<h1>STOP!!!</h1><p>IF YOU SEE THIS DO NOT EDIT THIS FILE!!! AN ERROR OCCURED ' +
        'AND EDITING THIS FILE CAN CAUSE DATA LOSS!!! RELOAD THE APPLICATION!!!</p>',
    onUpdate: saveFile,
});

onMounted(loadFile);

watch(
    () => props.file,
    async (path: string) => {
        // Load the file content when a new file is selected
        let content = await invoke<string>('get_markdown_file', { path });
        console.debug('load', content);

        ignoreFirstSave.value = true;
        editor.commands.setContent(content, { contentType: 'markdown' });
    }
);

async function loadFile() {
    const path = props.file;

    let content = await invoke<string>('get_markdown_file', { path });
    console.debug('load', content);

    ignoreFirstSave.value = true;
    editor.commands.setContent(content, { contentType: 'markdown' });
}

async function saveFile() {
    if (!props.file) return;
    if (ignoreFirstSave.value) {
        ignoreFirstSave.value = false;
        return;
    }

    // Get markdown content from the editor
    const content = editor.getMarkdown();
    console.debug('save', content);

    // Save the file content whenever it changes
    await invoke('save_markdown_file', {
        path: props.file,
        content,
    });
}

onUnmounted(() => {
    editor.destroy();
});
</script>
