# Runs the desktop application binary tests on every push to a pull request which has
# changes to rust code. If a Pull Request has no Rust-related changes, this workflow
# will not run.
name: Cargo Test

on:
  pull_request:
    paths:
      - 'torii-desktop/**'
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build-test:
    name: Cargo Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run cargo tests
        run: cargo test --all --all-targets --workspace --locked --verbose

